modLoader="javafml"
loaderVersion="[29,)"
issueTrackerURL="https://github.com/Christofmeg/FastEntityTransfer/issues" #optional
license="The MIT License (MIT)"
[[mods]]
modId="fastentitytransfer"
version="${file.jarVersion}"
displayName="Fast Entity Transfer"
displayURL="https://github.com/Christofmeg/FastEntityTransfer" #optional
logoFile="pack.png"
authors="Christofmeg"
credits="Abbie"
description="Factorio styled Fast Entity Transfer. CTRL + LEFT/RIGHT CLICK with items that are suitable for Blasting/Smelting/Smoking."
[[dependencies.fastentitytransfer]]
    modId="forge"
    mandatory=true
    versionRange="[29,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fastentitytransfer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"
