modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Christofmeg/FastEntityTransfer/issues" #optional
license="MIT License https://github.com/Christofmeg/FastEntityTransfer/blob/1.18.X/LICENSE"
[[mods]]
modId="fastentitytransfer"
version="1.18.x-1.0.0"
displayName="Fast Entity Transfer"
displayURL="https://github.com/Christofmeg/FastEntityTransfer" #optional
logoFile="pack.png"
#credits=""
authors="Christofmeg"
description='''
Factorio styled Fast Entity Transfer. Activated by CTRL + LEFT CLICK with items that are suitable for Blasting/Smelting/Smoking.
'''
[[dependencies.fastentitytransfer]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fastentitytransfer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"