modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Christofmeg/FastEntityTransfer/issues" #optional
license="The MIT License (MIT)"
[[mods]]
modId="fastentitytransfer"
version="${version}"
displayName="Fast Entity Transfer"
displayURL="https://github.com/Christofmeg/FastEntityTransfer" #optional
logoFile="icon.png"
authors="Christofmeg"
credits="Abbie"
description="Factorio styled Fast Entity Transfer. CTRL + LEFT/RIGHT CLICK with items that are suitable for Blasting/Smelting/Smoking."
[[dependencies.fastentitytransfer]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fastentitytransfer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,1.21)"
    ordering="NONE"
    side="BOTH"