modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Christofmeg/FastEntityTransfer/issues" #optional
license="${mod_license}"
[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://github.com/Christofmeg/FastEntityTransfer" #optional
    logoFile="icon.png"
    authors="${mod_authors}"
    credits="Abbie"
    description="${mod_description}"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"